### ISSUE TITLE
ARM无法启动

### ISSUE THREAD

**Issue by Wenbobobo** [duo/octopus#1]
使用的是Octopus-Wechat Hook
终端输出：
armbian:Octopuswx:# docker-compose up
Pulling octopus-wechat (lxduo/octopus-wechat:latest)...
latest: Pulling from lxduo/octopus-wechat
bb7d5a84853b: Pulling fs layer
6770d884c4ca: Pulling fs layer
4492e3431c45: Pulling fs layer
489a5e619cf1: Waiting
dc2b599b494d: Pull complete
7da118dfd759: Pull complete
6479dda2349e: Pull complete
27beeb660306: Pull complete
8b198ec01dfb: Pull complete
2330e6709ff5: Pull complete
0580846f9751: Pull complete
71464f4fc36f: Pull complete
07f320282ffc: Pull complete
a6308aac6678: Pull complete
98e390ac2ddd: Pull complete
4f4fb700ef54: Pull complete
2d684f3c1180: Pull complete
e7d6c08ede33: Pull complete
6a400a62b17e: Pull complete
007b830795a5: Pull complete
b19e28929e4b: Pull complete
151c340a9cfd: Pull complete
ac498385fa6a: Pull complete
f351e7cf29df: Pull complete
2419e81e1123: Pull complete
afb569d97b5f: Pull complete
Digest: sha256:73fd9ba3355a13fb90213be0ba621bd03ee6cbecb3db54d229f7ce0c6945f914
Status: Downloaded newer image for lxduo/octopus-wechat:latest
Creating octopus ... done
Creating octopus-wechat ... done
Attaching to octopus, octopus-wechat
octopus           | time="2023-11-21 21:26:31" level=info msg="MasterService starting for Wehcat2TG_bbot"
octopus           | time="2023-11-21 21:26:31" level=info msg="LimbService starting to listen on 0.0.0.0:11111"
octopus-wechat    | Start agent manager...
octopus-wechat    | Initialize agent...
octopus-wechat    | Create agent folder
octopus-wechat    | Download agent
octopus-wechat    | Download dll
octopus-wechat    | Start vnc...
octopus-wechat    | Start agent...
octopus-wechat    | Start agent manager...
octopus-wechat    | Initialize agent...
octopus-wechat    | Start vnc...
octopus-wechat    | Start agent...
octopus-wechat exited with code 0

不知道是不是armbian的问题....不太清楚怎么看详细的记录

**Comment by Wenbobobo** [comment]
**/root/Octopuswx/docker-compose.yml：**
version: "3.8"
services:
  octopus:
    hostname: octopus
    container_name: octopus
    image: lxduo/octopus:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./octopus:/data
    networks:
      - octopus-net

  octopus-wechat:
    hostname: octopus-wechat
    container_name: octopus-wechat
    image: lxduo/octopus-wechat:latest
    restart: unless-stopped
    depends_on:
      - octopus
    environment:
      TZ: Asia/Shanghai
      VNCPASS: <your vnc password>
    ports:
      - 5905:5905
    volumes:
      - ./octopus-wechat/configure.yaml:/home/user/configure.yaml
    networks:
      - octopus-net

networks:
  octopus-net:
    attachable: true

**/root/Octopuswx/octopus-wechat/configure.yaml：**
limb:

service:
  addr: ws://octopus:11111
  secret: 86003067

log:
  level: info
感激不尽！

**Comment by Wenbobobo** [comment]
补充：
使用docker logs
**octopus-WeChat：**
time="2023-11-21 21:26:31" level=info msg="MasterService starting for Wehcat2TG_bbot"
time="2023-11-21 21:26:31" level=info msg="LimbService starting to listen on 0.0.0.0:11111"
time="2023-11-21 21:37:36" level=info msg="LimbService stopping"
time="2023-11-21 21:37:36" level=info msg="MasterService stopping"
**octopus：**
Start agent manager...
Initialize agent...
Start vnc...
Start agent...
......
Stop agent...
Stop vnc...

**Comment by Wenbobobo** [comment]
再次docker-compose up之后出现了报错：

> Starting octopus ... done
Starting octopus-wechat ... done
Attaching to octopus, octopus-wechat
octopus           | time="2023-11-21 22:33:31" level=info msg="MasterService starting for Wehcat2TG_bbot"
octopus           | time="2023-11-21 22:33:31" level=info msg="LimbService starting to listen on 0.0.0.0:11111"
octopus-wechat    | Start agent manager...
octopus-wechat    | Initialize agent...
octopus-wechat    | Start vnc...
octopus-wechat    | Start agent...
octopus           | 2023/11/21 22:33:37 Failed to get updates; sleeping 1s: unable to getUpdates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
octopus           | 2023/11/21 22:33:41 Failed to get updates; sleeping 1s: unable to getUpdates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

**Comment by duo** [comment]
> 使用的是Octopus-Wechat Hook 终端输出： armbian:Octopuswx:# docker-compose up Pulling octopus-wechat (lxduo/octopus-wechat:latest)... latest: Pulling from lxduo/octopus-wechat bb7d5a84853b: Pulling fs layer 6770d884c4ca: Pulling fs layer 4492e3431c45: Pulling fs layer 489a5e619cf1: Waiting dc2b599b494d: Pull complete 7da118dfd759: Pull complete 6479dda2349e: Pull complete 27beeb660306: Pull complete 8b198ec01dfb: Pull complete 2330e6709ff5: Pull complete 0580846f9751: Pull complete 71464f4fc36f: Pull complete 07f320282ffc: Pull complete a6308aac6678: Pull complete 98e390ac2ddd: Pull complete 4f4fb700ef54: Pull complete 2d684f3c1180: Pull complete e7d6c08ede33: Pull complete 6a400a62b17e: Pull complete 007b830795a5: Pull complete b19e28929e4b: Pull complete 151c340a9cfd: Pull complete ac498385fa6a: Pull complete f351e7cf29df: Pull complete 2419e81e1123: Pull complete afb569d97b5f: Pull complete Digest: sha256:73fd9ba3355a13fb90213be0ba621bd03ee6cbecb3db54d229f7ce0c6945f914 Status: Downloaded newer image for lxduo/octopus-wechat:latest Creating octopus ... done Creating octopus-wechat ... done Attaching to octopus, octopus-wechat octopus | time="2023-11-21 21:26:31" level=info msg="MasterService starting for Wehcat2TG_bbot" octopus | time="2023-11-21 21:26:31" level=info msg="LimbService starting to listen on 0.0.0.0:11111" octopus-wechat | Start agent manager... octopus-wechat | Initialize agent... octopus-wechat | Create agent folder octopus-wechat | Download agent octopus-wechat | Download dll octopus-wechat | Start vnc... octopus-wechat | Start agent... octopus-wechat | Start agent manager... octopus-wechat | Initialize agent... octopus-wechat | Start vnc... octopus-wechat | Start agent... octopus-wechat exited with code 0
> 
> 不知道是不是armbian的问题....不太清楚怎么看详细的记录

octopus-wechat 这个跑的是 x86 windows 的微信呐

**Comment by duo** [comment]
> 再次docker-compose up之后出现了报错：
> 
> > Starting octopus ... done
> > Starting octopus-wechat ... done
> > Attaching to octopus, octopus-wechat
> > octopus           | time="2023-11-21 22:33:31" level=info msg="MasterService starting for Wehcat2TG_bbot"
> > octopus           | time="2023-11-21 22:33:31" level=info msg="LimbService starting to listen on 0.0.0.0:11111"
> > octopus-wechat    | Start agent manager...
> > octopus-wechat    | Initialize agent...
> > octopus-wechat    | Start vnc...
> > octopus-wechat    | Start agent...
> > octopus           | 2023/11/21 22:33:37 Failed to get updates; sleeping 1s: unable to getUpdates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
> > octopus           | 2023/11/21 22:33:41 Failed to get updates; sleeping 1s: unable to getUpdates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

这种应该是之前的 octopus 没退出，导致现在同时有两个在运行

**Comment by Wenbobobo** [comment]
是上游的上游的docker-wechat没支持，改天把wine换成quc?从头构建一遍
