### ISSUE TITLE
Bad Request: message is too long

### ISSUE THREAD

**Issue by Wenbobobo** [duo/octopus#2]
前几天突然发现无法绑定新群聊了，在绑定的TG群组里无法通过命令调出bot，但是神奇的是在Archive群组里可以正常调出bot，如果尝试私聊也会正常提醒。
登录VNC发现正常运行（有个升级弹窗，手动关掉之后依旧）
目前也可以正常收发消息，只是全都去Archive了.....
![image](https://github.com/duo/octopus/assets/78262508/52351b09-e38e-4890-8292-569f961d8775)
查看octopus的Docker log（wechat的log好像没什么有用信息）发现每当尝试调出bot失败时都会发：

...
time="2023-12-06 11:xx:xx" level=info msg="an error occurred while handling update: unable to sendMessage: Bad Request: message is too long"
想请教下可能是什么问题？非常感谢！

**Comment by duo** [comment]
这个还真没遇到过，这个报错是尝试给 Telegram 发送的消息长度超过 4096 个字符出现的，但是 /link 返回的结果是做了分页的，不应该会超啊...

**Comment by duo** [comment]
提交了个新版本 f795bd0399eae194436cbc2824d70b37f8b8bbf7 增加了个 `page_size` 的配置项，默认是10，试着减小看看（不知道是不是有些好友或者群组的名字超长导致的）

**Comment by Wenbobobo** [comment]
> 提交了个新版本 [f795bd0](https://github.com/duo/octopus/commit/f795bd0399eae194436cbc2824d70b37f8b8bbf7) 增加了个 `page_size` 的配置项，默认是10，试着减小看看（不知道是不是有些好友或者群组的名字超长导致的）

![image](https://github.com/duo/octopus/assets/78262508/38dc410a-2ff1-4a4c-a8e9-ee2e13659b9d)
仍然出现同样问题，而且在别的群组（Archive和新建的）都没问题。这个群组已经绑定了太多群了，很难再迁移什么的（以后可以加个迁移绑定的功能？🥰）而且tg无法更改默认话题，不知道咋整了

**Comment by Wenbobobo** [comment]
目前  page_size: 5 是减小到5

**Comment by duo** [comment]
原来是绑定了太多群啊，那我大概知道问题在哪了...
试试刚推的...

**Comment by Wenbobobo** [comment]
> 原来是绑定了太多群啊，那我大概知道问题在哪了... 试试刚推的...

好像还是这样....？

```
octopus-wechat    | err:vkd3d_create_vk_device: Failed to create Vulkan device, vr -7.
octopus           | time="2024-01-06 16:29:xx" level=info msg="an error occurred while handling update: unable to sendMessage: Bad Request: message is too long"
```
我是 docker container stop→docker container prune→docker-compose up 这样（page_size: 10）

**Comment by duo** [comment]
看看和 https://hub.docker.com/r/lxduo/octopus/tags 最新的 DIGEST 是否匹配？
不然 `docker-compose pull` 更新下吧

**Comment by Wenbobobo** [comment]
可以力，感谢！

_非常好项目，使🐉的🐎旋转_
